#!/bin/bash

### BEGIN INIT INFO
# Provides:          nfsceph
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    +ceph $remote_fs $named $network $time
# Required-Stop:     +ceph $remote_fs $named $network $time
# Short-Description: Start NFS for Ceph distributed file system at boot time
# Description:       Enable NFS for Ceph distributed file system services.
### END INIT INFO

test -f /etc/init.d/functions && . /etc/init.d/functions
test -f /lib/lsb/init-functions && . /lib/lsb/init-functions

prog=nfsceph
lockfile=/var/lock/subsys/$prog
nfsceph=/usr/sbin/$prog

[ -f $nfsceph ] || exit 1
[ -f /etc/sysconfig/nfsceph ] || exit 2

. /etc/sysconfig/nfsceph

start() {
    echo -n $"Starting nfsceph: "
    $nfsceph mapall &> /dev/null
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success || failure
    echo
    touch $lockfile
    return $RETVAL
}

status() {
#    [ -f $lockfile ] || exit 3
    $nfsceph export
}

stop() {
    echo -n $"Stopping nfsceph: "
    $nfsceph unmapall &> /dev/null
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success || failure
    rm -f $lockfile
    echo
    return $RETVAL
}

restart() {
    stop
    start
}

save() {
	echo "save, EXPORTS=$EXPORTS"
	$nfsceph export
    $nfsceph export > $EXPORTS
}

# See how we were called.
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status
    ;;
  save)
    save
    ;;
  restart|force-reload)
    stop
    start
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|force-reload|save}"
    exit 2
esac
