#!/bin/bash
#
# chkconfig: - 35 50
# description: sets up nfsceph file shares

### BEGIN INIT INFO
# Provides: nfsceph
# Short-Description: sets up nfsceph file shares
# Description: sets up nfsceph file shares
### END INIT INFO

# Source function library.
. /etc/init.d/functions

prog=nfsceph
lockfile=/var/lock/subsys/$prog
nfsceph=/usr/bin/$prog

[ -f /usr/bin/nfsceph ] || exit 1
[ -f /etc/sysconfig/nfsceph ] || exit 2

. /etc/sysconfig/nfsceph

start() {
	echo -n $"Starting nfsceph: "
    $nfsceph mountall &> /dev/null
    $nfsceph exportall &> /dev/null
	RETVAL=$?
	[ $RETVAL -eq 0 ] && success || failure
	echo
    touch $lockfile
	return $RETVAL
}

status() {
#	[ -f $lockfile ] || exit 3
    $nfsceph export
}

stop() {
    # save config first
    [ $SAVE_CONFIG == "yes" ] && $nfsceph export > $EXPORTS

	echo -n $"Stopping nfsceph: "
    /usr/bin/nfsceph unexportall &> /dev/null
    /usr/bin/nfsceph umountall &> /dev/null
	RETVAL=$?
	[ $RETVAL -eq 0 ] && success || failure
	rm -f $lockfile
	echo
	return $RETVAL
}

restart() {
	stop
    start
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status
	;;
  restart|force-reload)
	stop
	start
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|force-reload}"
	exit 2
esac
